[package]
name = "{{project-name}}"
description = "{{project-description}}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
{%- if license != "None" %}
license.workspace = true
{%- endif %}
publish.workspace = true
build = "build.rs"

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"

[lib]
name = "{{crate_name}}"
path = "src/lib.rs"

[dependencies]
{{project-name}}-api = { workspace = true }
{{project-name}}-config = { workspace = true }
{{project-name}}-core = { workspace = true }
{{project-name}}-domain = { workspace = true }
{{project-name}}-infra = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
vergen-gitcl = { workspace = true }

[dev-dependencies]
{{project-name}}-test-utils = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
